db:
  image: mongo
  ports: 
    - "27017:27017"
  volumes:
    - ./data/db:/data/db
  restart: always
web:
  build: .
  volumes:
    - ./:/app
  ports:
    - "3000:3000"
  links:
    - db
  command: npm run dev